### ISSUE TITLE
이미지 링크 깨지는 버그

### ISSUE THREAD

**Issue by the6thm0nth** [ftto/defol#1]
- 현재 url: https://ftto.github.io/defol
: 아마 이전에는 `/` 경로로 이미지를 불러오던게 지금은 url이 바뀌어서 `/defol/` 뒤로 이미지들이 붙기 때문에 깨진걸꺼에요. 한 번 확인해봐주세요.

**Comment by mozodev** [comment]
오 재밌는 걸 하시는 듯 하군요~ ㅎㅎ

**Comment by amiru11** [comment]
@mozodev 감사합니다!

**Comment by the6thm0nth** [comment]
@mozedev ㅋㅋㅋㅋ 영택님!!! 한번 보러갈게요!
